services:
  postgres:
    image: postgres:latest
    container_name: postgres-influencer-platform
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: influencer-platform
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

volumes:
  postgres_test_data:
    driver: local
