services:
  postgres:
    image: postgres:latest
    container_name: postgres-course-platform
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: course-platform
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: rabbitmq-course-platform
    ports:
      - "5672:5672"   # Message broker port
      - "15672:15672" # Web interface port
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/data
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 20s
      timeout: 10s
      retries: 5

volumes:
  postgres_test_data:
    driver: local
  rabbitmq_data:
    driver: local
